const listaProdutos = [
    // --- CATEGORIA: CASAL (PADRÃO) ---
    { nome: "Cobertor Kyor Jolitex", categoria: "casal", preco: 219.00, imagem: "https://i.postimg.cc/qvp2b1q2/kyor.png", descricao: "Gramatura 415 g/m²" },
    { nome: "Edredom Capetown Casal", categoria: "casal", preco: 339.00, imagem: "https://i.postimg.cc/XY9DFHhd/capetow.png", descricao: "Praticidade e conforto" },
    { nome: "Colcha Teka Allegro Plus", categoria: "casal", preco: 89.00, imagem: "https://i.postimg.cc/44M80RRY/colcha-teka.png", descricao: "Casal Padrão" },
    { nome: "Kit Peseira 4 peças", categoria: "casal", preco: 89.00, imagem: "https://i.postimg.cc/xdfXrPkc/kit-peseira.png", descricao: "Casal Padrão com baguete" },
    { nome: "Manta Living Art 300", categoria: "casal", preco: 119.00, imagem: "https://i.postimg.cc/wxtxZFRT/living-ar.png", descricao: "Toque de seda" },
    { nome: "Jogo Premiun Plus 100% Algodão", categoria: "casal", preco: 139.00, imagem: "https://i.postimg.cc/hGDXF0Jv/jogo-premiun.jpg", descricao: "4 peças" },
    { nome: "Jogo de Cama Essenciale", categoria: "casal", preco: 149.00, imagem: "https://i.postimg.cc/SKSn0GXK/jogo-de-cama-essenciale.jpg", descricao: "100% Algodão" },
    { nome: "Jogo de Cama Dona do Lar", categoria: "casal", preco: 89.00, imagem: "https://i.postimg.cc/W4NdR7Dp/dona-do-lar.jpg", descricao: "3 Peças" },
    { nome: "Jogo de Cama Microtec 200 fios", categoria: "casal", preco: 120.00, imagem: "https://i.postimg.cc/BvSjWC8n/jogo-de-cama-4-pecas-microte.jpg", descricao: "Toque macio" },
    { nome: "Jogo de Lençol Döhler", categoria: "casal", preco: 249.00, imagem: "https://i.postimg.cc/9fmD3B4W/ambar.png", descricao: "3 Peças Casal" },
    { nome: "Colcha Sicília Niazitex", categoria: "casal", preco: 219.00, imagem: "https://i.postimg.cc/q71zpCn2/sicilia.jpg", descricao: "Kit 3 peças" },
    { nome: "Cobreleito Plaza Lavive", categoria: "casal", preco: 419.00, imagem: "https://i.postimg.cc/KYG1X5K5/plaza.png", descricao: "3 Pçs Dupla Face" },
    { nome: "Kit Colcha Piquet", categoria: "casal", preco: 279.00, imagem: "https://i.postimg.cc/MG6nkYcV/piquet.png", descricao: "100% Algodão" },
    { nome: "Colcha Milão Corttex", categoria: "casal", preco: 117.00, imagem: "https://i.postimg.cc/xdfXrPkk/milao.jpg", descricao: "Casal Padrão" },
    { nome: "Kit Colcha Paris Corttex", categoria: "casal", preco: 117.00, imagem: "https://i.postimg.cc/k5J2ryVc/ponto-palito.png", descricao: "3 Peças Dupla face" },
    { nome: "Saia Box Microfibra", categoria: "casal", preco: 179.00, imagem: "https://i.postimg.cc/k5J2ryVc/ponto-palito.png", descricao: "Ponto Palito" },
    { nome: "Saia em Malha Adomes", categoria: "casal", preco: 69.00, imagem: "https://i.postimg.cc/cJFrd8Yw/saia-malha.png", descricao: "Casal" },
    { nome: "Pillow Top Casal Niazitex", categoria: "casal", preco: 319.00, imagem: "https://i.postimg.cc/dtyMmxkj/pillowtopcasalniazitex.png", descricao: "Conforto Extra" },
    { nome: "Protetor Impermeável Algodão", categoria: "casal", preco: 149.00, imagem: "https://i.postimg.cc/R0gNvnfH/protetor-impermeavel.png", descricao: "100% Algodão" },

    // --- CATEGORIA: SOLTEIRO ---
    { nome: "Jogo lençol Premium Solteiro", categoria: "solteiro", preco: 119.00, imagem: "https://i.postimg.cc/3JJ4k2kk/premiun.png", descricao: "4 Peças - 100% Algodão" },
    { nome: "Jogo lençol Teka Solteiro", categoria: "solteiro", preco: 169.00, imagem: "https://i.postimg.cc/3JSymWG8/teka.png", descricao: "150 Fios - Algodão" },
    { nome: "Jogo lençol Ambar Solteiro", categoria: "solteiro", preco: 239.00, imagem: "https://i.postimg.cc/TYYLKnKY/ambar.png", descricao: "3 Peças - Döhler" },
    { nome: "Kit colcha Londres Solteiro", categoria: "solteiro", preco: 199.00, imagem: "https://i.postimg.cc/DyyJS1Sw/londres.png", descricao: "Matelassê 2 peças" },
    { nome: "Colcha Sicilia Solteiro", categoria: "solteiro", preco: 139.00, imagem: "https://i.postimg.cc/yYYgD0D3/sicilia.png", descricao: "Ultrassônica 2 peças" },
    { nome: "Colcha Paris Solteiro", categoria: "solteiro", preco: 87.00, imagem: "https://i.postimg.cc/5NNYX8X0/paris.png", descricao: "Dupla Face 2 peças" },
    { nome: "Colcha Plaza Solteiro", categoria: "solteiro", preco: 329.00, imagem: "https://i.postimg.cc/J44Dsjst/plaza.png", descricao: "Lavive Luxo 2 peças" },
    { nome: "Colcha Montblack Solteiro", categoria: "solteiro", preco: 119.00, imagem: "https://i.postimg.cc/3JJ4k2kw/montblac.png", descricao: "Microfibra Corttex" },
    { nome: "Edredom Dona do Lar Solteiro", categoria: "solteiro", preco: 169.00, imagem: "https://i.postimg.cc/9FFRDyDm/donadolar.png", descricao: "Dupla Face Macio" },
    { nome: "Cobertor Capetowne Solteiro", categoria: "solteiro", preco: 320.00, imagem: "https://i.postimg.cc/fTTtVYVW/capetown.png", descricao: "Gramatura 600g Luxo" },
    { nome: "Saia Box Solteiro", categoria: "solteiro", preco: 149.00, imagem: "https://i.postimg.cc/hPMhLvkG/saiakaacyumaraqueen.png", descricao: "Ponto Palito" },

    // --- CATEGORIA: QUEEN ---
    { nome: "Jogo lençol Premium Queen", categoria: "queen", preco: 165.00, imagem: "https://i.postimg.cc/7YXb3hFZ/premiun-Queen.jpg", descricao: "4 Peças - 100% Algodão" },
    { nome: "Jogo lençol Ambar Queen", categoria: "queen", preco: 329.00, imagem: "https://i.postimg.cc/X7xXfqRS/ambar-queen.png", descricao: "4 Peças - Döhler" },
    { nome: "Jogo lençol Teka Queen", categoria: "queen", preco: 249.00, imagem: "https://i.postimg.cc/gk4rVjCx/teka-queen.png", descricao: "150 Fios - 4 Peças" },
    { nome: "Kit colcha Piquet Queen", categoria: "queen", preco: 339.00, imagem: "https://i.postimg.cc/X7xXfqRN/piquetqueen.png", descricao: "100% Algodão Dohler" },
    { nome: "Kit colcha Plaza Queen", categoria: "queen", preco: 449.00, imagem: "https://i.postimg.cc/bNLdxr7N/plaza-queen.png", descricao: "Lavive Luxo 3 peças" },
    { nome: "Kit colcha Londres Queen", categoria: "queen", preco: 299.00, imagem: "https://i.postimg.cc/Dy5mr09h/londresqueen.png", descricao: "Matelassê 3 peças" },
    { nome: "Kit colcha Sicilia Queen", categoria: "queen", preco: 199.00, imagem: "https://i.postimg.cc/zXp3Cvs3/sicili.png", descricao: "Ultrassônica 3 peças" },
    { nome: "Kit Coordenado Charlote Queen", categoria: "queen", preco: 580.00, imagem: "https://i.postimg.cc/rFgz1sBq/charlote.png", descricao: "Jogo Completo Luxo" },
    { nome: "Cobertor Capetowne Queen", categoria: "queen", preco: 399.00, imagem: "https://i.postimg.cc/ncTM4ryH/capetown.png", descricao: "Gramatura Alta" },
    { nome: "Saia Box Queen", categoria: "queen", preco: 189.00, imagem: "https://i.postimg.cc/hPMhLvkG/saiakaacyumaraqueen.png", descricao: "Kacyumara Ponto Palito" },

    // --- CATEGORIA: KING ---
    { nome: "Jogo lençol Premium King", categoria: "king", preco: 239.00, imagem: "https://i.postimg.cc/cHq5FspN/premiunking.png", descricao: "4 Peças - 100% Algodão" },
    { nome: "Jogo lençol Ambar King", categoria: "king", preco: 389.00, imagem: "https://i.postimg.cc/JhH23y2R/Ambarking.png", descricao: "4 Peças - Luxo" },
    { nome: "Jogo lençol Teka King", categoria: "king", preco: 289.00, imagem: "https://i.postimg.cc/9M3NLW6C/tekaking.png", descricao: "150 Fios - Algodão" },
    { nome: "Kit colcha Plaza King", categoria: "king", preco: 489.00, imagem: "https://i.postimg.cc/9M3NLW6H/plazaking.png", descricao: "Lavive Luxo 3 peças" },
    { nome: "Kit colcha Londres King", categoria: "king", preco: 349.00, imagem: "https://i.postimg.cc/FRtnT92q/londresking.png", descricao: "Matelassê 3 peças" },
    { nome: "Kit Coordenado Charlote King", categoria: "king", preco: 630.00, imagem: "https://i.postimg.cc/4dCFWJrj/charloteking.png", descricao: "Jogo Completo Luxo" },
    { nome: "Colcha Sicilia King", categoria: "king", preco: 219.00, imagem: "https://i.postimg.cc/DZVYx29T/sicilia.png", descricao: "Ultrassônica 3 peças" },
    { nome: "Cobertor Capetowne King", categoria: "king", preco: 528.00, imagem: "https://i.postimg.cc/hjF32SH6/capetownking.png", descricao: "Alta Gramatura" },
    { nome: "Saia Box King", categoria: "king", preco: 199.00, imagem: "https://i.postimg.cc/k5J2ryVc/ponto-palito.png", descricao: "Kacyumara Ponto Palito" },

    // --- CATEGORIA: BANHO ---
    { nome: "Toalha de Banho Lumina", categoria: "banho", preco: 79.00, imagem: "https://i.postimg.cc/pdPHXWtf/lumina.jpg", descricao: "Karsten" },
    { nome: "Toalha de Banho Prisma", categoria: "banho", preco: 48.00, imagem: "https://i.postimg.cc/SKmhNSpR/jogo-prisma-variedade.png", descricao: "Döhler" },
    { nome: "Toalha de Banho Wave", categoria: "banho", preco: 54.00, imagem: "https://i.postimg.cc/wBFd1C6R/toalha-banho-rosto-corttex-macio-wave.jpg", descricao: "Corttex" },
    { nome: "Toalha Wave Banhão", categoria: "banho", preco: 64.00, imagem: "https://i.postimg.cc/wBFd1C6Q/wave-banhao.jpg", descricao: "Corttex" },
    { nome: "Toalha Duomo Fio Penteado", categoria: "banho", preco: 69.00, imagem: "https://i.postimg.cc/9fchFmjr/Banho-Duomo-Jan25.jpg", descricao: "" },
    { nome: "Jogo de Toalha 5 peças", categoria: "banho", preco: 199.00, imagem: "https://i.postimg.cc/Lsmp69M4/jogo-mafratex.png", descricao: "100% algodão" },
    { nome: "Jogo Toalha Banho e Rosto", categoria: "banho", preco: 74.00, imagem: "https://i.postimg.cc/GpbChL1n/jogo-2-pecas-dohler.png", descricao: "Döhler" },
    { nome: "Roupão Toque de Seda", categoria: "banho", preco: 149.00, imagem: "https://i.postimg.cc/Jhqt7nRj/roupaotoquedeseda.png", descricao: "Corttex M/F" },
    { nome: "Jogo de Banheiro Riviera", categoria: "banho", preco: 110.00, imagem: "https://i.postimg.cc/SK8jMNnw/riviera.png", descricao: "Jolitex" },
    { nome: "Jogo de Banheiro Oasis", categoria: "banho", preco: 69.00, imagem: "https://i.postimg.cc/3wpWvJkV/jogo-de-banheiro-oasis.png", descricao: "3 Peças" },
    { nome: "Piso Royal 100% Algodão", categoria: "banho", preco: 22.00, imagem: "https://i.postimg.cc/bvbdtNZ4/piso-Royal.png", descricao: "Döhler" },
    { nome: "Jogo de Toalhas Lollipop 5 Peças", categoria: "banho", preco: 339.00, imagem: "https://i.postimg.cc/vmzD8BGD/5pecaslolipopi.png", descricao: "Premium" },
    { nome: "Lixeira em Inox 5L", categoria: "banho", preco: 99.00, imagem: "https://i.postimg.cc/7LVbP6qL/lixeira.png", descricao: "Banheiro" },
    { nome: "Jogo de Toalha Mafratex 5 pçs", categoria: "banho", preco: 189.00, imagem: "https://i.postimg.cc/HL2jWxTx/mafratex.png", descricao: "100% Algodão Premium" },
    { nome: "Jogo de Toalha Buettner 5 pçs", categoria: "banho", preco: 269.00, imagem: "https://i.postimg.cc/5t3j90fy/buettner.png", descricao: "Melody Premium Buettner" },
    { nome: "Kit Piso Döhler 5 pçs + Difusor", categoria: "banho", preco: 126.00, imagem: "https://i.postimg.cc/N04LGMQT/piso.png", descricao: "5 Pisos + Fragrância" },
    { nome: "Roupão Velour Masculino M", categoria: "banho", preco: 169.00, imagem: "https://i.postimg.cc/jjXCq5RP/velour.png", descricao: "Döhler - Masculino" },
    { nome: "Roupão Dohler Feminino M", categoria: "banho", preco: 149.00, imagem: "https://i.postimg.cc/W4ntp3sm/velour2.png", descricao: "Döhler - Feminino" },

    // --- CATEGORIA: MESA ---
    { nome: "Americano Souplast Redondo", categoria: "mesa", preco: 10.00, imagem: "https://i.postimg.cc/Kjsg5pmS/jogo-americano.png", descricao: "Unidade" },
    { nome: "Kit Jogo americano Redondo 6pçs", categoria: "mesa", preco: 60.00, imagem: "https://i.postimg.cc/Kjsg5pmS/jogo-americano.png", descricao: "Conjunto" },
    { nome: "Jogo Tapete Cozinha Gourmet", categoria: "mesa", preco: 149.00, imagem: "https://i.postimg.cc/66LKG4YF/jolitex-tapte-goumet.png", descricao: "3 Peças" },
    { nome: "Pano de Copa Tecilar", categoria: "mesa", preco: 9.00, imagem: "https://i.postimg.cc/4yFh12XG/tecilar.png", descricao: "Döhler" },
    { nome: "Pano de Prato Felpudo", categoria: "mesa", preco: 18.00, imagem: "https://i.postimg.cc/0jHJCXPH/atoalhado.png", descricao: "Döhler" },
    { nome: "Guardanapo ponto palito", categoria: "mesa", preco: 8.00, imagem: "https://i.postimg.cc/D0Ybcpn9/guardanapo.png", descricao: "Tecido" },
    { nome: "Manta de Jarra", categoria: "mesa", preco: 59.00, imagem: "https://i.postimg.cc/05dvJKcT/manta-de-jarra.png", descricao: "Pedrarias" },
    { nome: "Escorredor de Louça", categoria: "mesa", preco: 55.00, imagem: "https://i.postimg.cc/4yFh12XC/escorredor-de-louca-buettner.png", descricao: "Buttener" },
    { nome: "Kit 10 Panos de Copa Tecilar", categoria: "mesa", preco: 90.00, imagem: "https://i.postimg.cc/Fs5fxwCd/tecilar.png", descricao: "Döhler - 10 unidades" },
    { nome: "Argolas para Guardanapo 6pçs", categoria: "mesa", preco: 96.00, imagem: "https://i.postimg.cc/KvSK5CpR/aegola.png", descricao: "Kit Decorativo" },

    // --- CATEGORIA: SALA ---
    { nome: "Capa de Cadeira 6 Peças", categoria: "sala", preco: 79.00, imagem: "https://i.postimg.cc/fyg0vqDr/capa-de-cadeira-6.png", descricao: "Malha - Jogo 6" },
    { nome: "Capa de Cadeira 4 Peças", categoria: "sala", preco: 65.00, imagem: "https://i.postimg.cc/2yXBx9r9/capa-de-cadeira.png", descricao: "Malha - Jogo 4" },
    { nome: "Cortina Sala Messina 3.00x2.50", categoria: "sala", preco: 359.00, imagem: "https://i.postimg.cc/G2DcfMP3/messina.png", descricao: "Jacquard Döhler Luxo" },
    { nome: "Cortina Janela Blackout", categoria: "sala", preco: 99.00, imagem: "https://i.postimg.cc/C18F2vCL/janela.png", descricao: "Bella Janela" },
    { nome: "Cortina Oxford", categoria: "sala", preco: 49.00, imagem: "https://i.postimg.cc/D0K23q5F/cortina-oxford.png", descricao: "3,00m x 2,60m" },
    { nome: "Manta para Sofá Marrocos", categoria: "sala", preco: 99.00, imagem: "https://i.postimg.cc/PqRJv78r/marrocos.png", descricao: "Döhler G" },
    { nome: "Cortina Carol Veneza 4.00x2.60", categoria: "sala", preco: 252.00, imagem: "https://i.postimg.cc/s2NxGLZF/carol.png", descricao: "Veneza - Grande" },
    { nome: "Tapete Sala Málaga 1.40x2.00", categoria: "sala", preco: 579.00, imagem: "https://i.postimg.cc/0NBjK4Jq/malaga.png", descricao: "Tapete Luxo para Centro" },
    { nome: "Bandeja Porta Controle", categoria: "sala", preco: 69.00, imagem: "https://i.postimg.cc/q75q6F69/bandeja.png", descricao: "Organizador para sofá" },
    { nome: "Kit 6 Capas Almofada Grippir", categoria: "sala", preco: 174.00, imagem: "https://i.postimg.cc/SKvRYPzh/gruipir.png", descricao: "Renda Grippir Decorativa" },

    // --- CATEGORIA: UTILITÁRIOS ---
    { nome: "Cozedor de Ovos Elétrico", categoria: "mesa", preco: 115.00, imagem: "https://i.postimg.cc/d3ST9NwX/cozedor-de-ovos.png", descricao: "Portátil" },
    { nome: "Omeleteira Elétrica", categoria: "mesa", preco: 199.00, imagem: "https://i.postimg.cc/4yFh12Xg/omeleteira.png", descricao: "Multilaser" },
    { nome: "Chaleira Elétrica 1,8L", categoria: "mesa", preco: 139.00, imagem: "https://i.postimg.cc/GtSsjgdM/chaleira.png", descricao: "Inox" },
    { nome: "Jogo de Panelas Cerâmica 9pçs", categoria: "mesa", preco: 690.00, imagem: "https://i.postimg.cc/s2Sq5QMQ/panelas.png", descricao: "Revestimento cerâmico" },
    { nome: "Faqueiro Alpha Premium 24pçs", categoria: "mesa", preco: 189.00, imagem: "https://i.postimg.cc/GpYVv844/faqueiro.png", descricao: "Aço Inox Premium" },
    { nome: "Panela Elétrica Multifuncional", categoria: "mesa", preco: 139.00, imagem: "https://i.postimg.cc/9fTKyRDr/panelaeletrica.png", descricao: "Praticidade" },
    { nome: "Mop de Limpeza Giratório", categoria: "mesa", preco: 79.00, imagem: "https://i.postimg.cc/pd84Khmr/mop.png", descricao: "Limpeza Prática" },
    { nome: "Frigideira Antiaderente 26cm", categoria: "mesa", preco: 199.00, imagem: "https://i.postimg.cc/wBJZDy1x/frigideira.jpg", descricao: "Tamanho grande" }
];
